"""Create user table

Revision ID: 0e064f3a36d2
Revises: e45a53c0d7d7
Create Date: 2018-11-29 14:19:59.351779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e064f3a36d2'
down_revision = 'e45a53c0d7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=280), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tweet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_column('tweet', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
